-- Data/Weights.lua -- GENERATED by tools/build_weights.py. Do not edit by hand.
-- Source: weights.json (PasslootBiS converter/data). Regenerate to update.

PLBiSScannerWeights_IsPlaceholder = false

PLBiSScannerWeights = {
	["Barbarian"] = {
		["Ancestry"] = { agility = 1.387, armorPenetration = 0.25, attackPower = 1, critRating = 0.5, expertise = 0.5, hasteRating = 0.55, hitRating = 0.5, strength = 1 },
		["Brutality"] = { agility = 2.195, armorPenetration = 0.45, attackPower = 1, critRating = 0.761, expertise = 0.5, hasteRating = 0.6, hitRating = 0.5, strength = 2.188, weaponDps = 14 },
		["Headhunting"] = { agility = 1.473, armorPenetration = 0.45, attackPower = 1, critRating = 0.65, hasteRating = 0.6, rangedAttackPower = 1, rangedDps = 14 },
	},
	["Bloodmage"] = {
		["Accursed"] = { agility = 1.947, armorPenetration = 0.3, attackPower = 1, critRating = 0.653, expertise = 0.5, hasteRating = 0.6, hitRating = 0.5, intellect = 0.119, spellDamage = 0.75, spellPower = 0.75, strength = 1.404, weaponDps = 14 },
		["Eternal"] = { agility = 2.967, armor = 0.2, armorPenetration = 0.15, attackPower = 1, critRating = 0.364, defense = 1.05, dodge = 0.9, expertise = 0.5, hasteRating = 0.35, hitRating = 0.5, intellect = 0.067, parry = 0.9, spellDamage = 0.25, spellPower = 0.25, stamina = 1.08, strength = 1.177, weaponDps = 14 },
		["Fleshweaver"] = { critRating = 0.5, hasteRating = 0.6, healingPower = 1, intellect = 0.091, spellDamage = 1, spellPower = 1, spirit = 0.621 },
		["Sanguine"] = { critRating = 0.9, hasteRating = 0.6, intellect = 0.165, spellDamage = 1, spellPenetration = 0.01, spellPower = 1, spirit = 0.27, stamina = 0.27 },
	},
	["Chronomancer"] = {
		["Artificer"] = { agility = 1.1, attackPower = 1, critRating = 0.7, hasteRating = 0.9, intellect = 0.1, rangedAttackPower = 1, rangedDps = 14, spellDamage = 0.7, spellPenetration = 0.5, spellPower = 0.7, spirit = 1.5 },
		["Infinite"] = { critRating = 0.75, hasteRating = 0.6, intellect = 0.096, spellDamage = 1, spellPenetration = 0.01, spellPower = 1, spirit = 0.46 },
		["Time"] = { critRating = 0.5, hasteRating = 0.65, healingPower = 1, intellect = 0.064, spellDamage = 1, spellPower = 1, spirit = 0.575 },
	},
	["Cultist"] = {
		["Corruption"] = { critRating = 0.9, hasteRating = 0.6, intellect = 0.507, spellDamage = 1, spellPenetration = 0.01, spellPower = 1 },
		["Dreadnought"] = { armor = 0.255, armorPenetration = 0.15, attackPower = 1, block = 1.8, blockValue = 0.24, critRating = 0.35, defense = 1.05, dodge = 0.9, expertise = 0.5, hasteRating = 0.35, hitRating = 0.5, intellect = 0.1, parry = 0.9, shieldBlockValue = 0.2, spellDamage = 0.5, spellPower = 0.5, stamina = 1.12, strength = 2.531, weaponDps = 14 },
		["Godblade"] = { armorPenetration = 0.3, attackPower = 1, critRating = 0.797, expertise = 0.5, hasteRating = 0.6, hitRating = 0.5, intellect = 1.271, spellDamage = 0.25, spellPower = 0.25, strength = 2.268, weaponDps = 14 },
		["Heretic"] = { armorPenetration = 0.2, attackPower = 1, critRating = 3, hasteRating = 0.4, intellect = 0.104, spellDamage = 0.4, spellPower = 0.4, strength = 1, weaponDps = 14 },
	},
	["Druid"] = {
		["Balance"] = { critRating = 0.6, hasteRating = 0.7, hitRating = 0.5, intellect = 0.6, spellPenetration = 0.5, spellPower = 1, spirit = 0.1 },
		["Feral"] = { agility = 2, armorPenetration = 1, attackPower = 1, critRating = 0.6, expertise = 0.5, feralAttackPower = 1.2, hasteRating = 0.4, hitRating = 0.5, strength = 2 },
		["Restoration"] = { critRating = 0.5, hasteRating = 0.8, healingPower = 1, intellect = 0.1, spellPower = 1, spirit = 0.9 },
	},
	["Felsworn"] = {
		["Infernal"] = { critRating = 1.242, hasteRating = 0.6, intellect = 0.414, spellDamage = 1, spellPenetration = 0.01, spellPower = 1, spirit = 0.517 },
		["Slayer"] = { agility = 2.5, armorPenetration = 0.3, attackPower = 1, critRating = 0.734, expertise = 0.5, hasteRating = 0.6, strength = 1, weaponDps = 14 },
		["Tyrant"] = { agility = 2.817, armor = 0.5, armorPenetration = 0.15, attackPower = 1, critRating = 0.35, defense = 1.05, dodge = 0.9, expertise = 0.5, hasteRating = 0.35, hitRating = 0.5, parry = 0.9, stamina = 2, strength = 1.135, weaponDps = 14 },
	},
	["Guardian"] = {
		["Gladiator"] = { agility = 0.617, armorPenetration = 0.45, attackPower = 1, critRating = 0.796, expertise = 0.5, hasteRating = 0.6, strength = 2.464, weaponDps = 14 },
		["Inspiration"] = { agility = 0.444, armorPenetration = 0.25, attackPower = 1, critRating = 0.6, expertise = 0.5, hasteRating = 0.55, hitRating = 0.5, strength = 2.16 },
		["Vanguard"] = { agility = 1, armor = 0.325, armorPenetration = 0.15, attackPower = 1, block = 0.75, blockValue = 0.33, critRating = 0.35, defense = 1.05, dodge = 0.9, expertise = 0.5, hasteRating = 0.35, hitRating = 0.5, parry = 0.9, shieldBlockValue = 0.2, stamina = 3, strength = 2, weaponDps = 14 },
	},
	["Hunter"] = {
		["Beast Mastery"] = { agility = 2, armorPenetration = 0.5, attackPower = 1, critRating = 0.5, hasteRating = 0.4, hitRating = 0.5, intellect = 0.1, stamina = 0.1, weaponDps = 14 },
		["Marksmanship"] = { agility = 2, armorPenetration = 1, attackPower = 1, critRating = 0.8, hasteRating = 0.5, hitRating = 0.5, intellect = 1.1, stamina = 0.1, weaponDps = 14 },
		["Survival"] = { agility = 2.5, armorPenetration = 1, attackPower = 1, critRating = 0.4, hasteRating = 0.8, hitRating = 0.5, intellect = 0.1, stamina = 0.1, strength = 1, weaponDps = 14 },
	},
	["Knight of Xoroth"] = {
		["Defiance"] = { agility = 1.127, armor = 0.2, armorPenetration = 0.15, attackPower = 1, block = 0.75, blockValue = 0.26, critRating = 0.376, defense = 1.05, dodge = 0.9, expertise = 0.5, hasteRating = 0.35, hitRating = 0.5, intellect = 0.064, parry = 0.9, shieldBlockValue = 0.2, spellDamage = 0.75, spellPower = 0.75, stamina = 1.06, strength = 2.549, weaponDps = 14 },
		["Hellfire"] = { agility = 0.585, armorPenetration = 0.3, attackPower = 0.75, critRating = 0.831, expertise = 0.5, hasteRating = 0.6, hitRating = 0.5, intellect = 1.163, spellDamage = 1, spellPower = 1, strength = 2.2, weaponDps = 14 },
		["War"] = { agility = 0.721, armorPenetration = 0.45, attackPower = 1, critRating = 1.024, expertise = 0.5, hasteRating = 0.6, strength = 2.398, weaponDps = 14 },
	},
	["Mage"] = {
		["Arcane"] = { critRating = 0.6, hasteRating = 0.6, hitRating = 0.5, intellect = 0.8, mp5 = 0.05, spellPenetration = 0.5, spellPower = 1, spirit = 0.3 },
		["Fire"] = { critRating = 0.9, hasteRating = 0.6, hitRating = 0.5, intellect = 0.1, mp5 = 0.01, spellPenetration = 0.5, spellPower = 1, spirit = 0.3 },
		["Frost"] = { critRating = 0.5, hasteRating = 0.8, hitRating = 0.5, intellect = 0.1, mp5 = 0.01, spellPenetration = 0.5, spellPower = 1, spirit = 0.3 },
		["Healer"] = { critRating = 0.6, hasteRating = 0.8, healingPower = 1, intellect = 0.8, mp5 = 0.4, spellPower = 1, spirit = 0.5 },
	},
	["Necromancer"] = {
		["Animation"] = { critRating = 0.6, hasteRating = 0.6, hitRating = 0.5, intellect = 0.051, spellDamage = 1, spellPenetration = 0.01, spellPower = 1 },
		["Death"] = { critRating = 0.63, hasteRating = 0.6, intellect = 0.054, spellDamage = 1, spellPenetration = 0.01, spellPower = 1 },
		["Rime"] = { critRating = 0.9, hasteRating = 0.6, intellect = 0.415, spellDamage = 1, spellPenetration = 0.01, spellPower = 1 },
	},
	["Paladin"] = {
		["Holy"] = { critRating = 0.4, hasteRating = 1, healingPower = 1, intellect = 2, mp5 = 0.2, spellPower = 1, spirit = 0.5 },
		["Protection"] = { agility = 0.5, armor = 0.1, attackPower = 1, block = 2, blockValue = 2, critRating = 0.1, defense = 2, dodge = 0.5, expertise = 0.5, hasteRating = 0.1, hitRating = 0.5, parry = 0.5, spellPower = 0.8, stamina = 2.5, strength = 1, weaponDps = 14 },
		["Retribution"] = { agility = 1, armorPenetration = 0.1, attackPower = 1, critRating = 1, expertise = 0.5, hasteRating = 0.4, hitRating = 1, intellect = 0.1, spellPower = 0.7, strength = 2.5, weaponDps = 14 },
	},
	["Priest"] = {
		["Discipline"] = { critRating = 0.2, hasteRating = 0.6, healingPower = 1, intellect = 0.4, mp5 = 0.3, spellPower = 1, spirit = 0.1, stamina = 0.01 },
		["Holy"] = { critRating = 0.6, hasteRating = 0.5, healingPower = 1, intellect = 0.5, mp5 = 0.3, spellPower = 1, spirit = 0.9 },
		["Shadow"] = { critRating = 0.6, hasteRating = 0.7, hitRating = 0.5, intellect = 0.1, spellPenetration = 0.5, spellPower = 1, spirit = 0.8 },
	},
	["Primalist"] = {
		["Geomancy"] = { armorPenetration = 0.5, critRating = 0.654, hasteRating = 0.6, hitRating = 0.5, intellect = 0.397, spellDamage = 1, spellPenetration = 0.01, spellPower = 1 },
		["Grovekeeper"] = { agility = 0.374, armorPenetration = 0.2, attackPower = 1, critRating = 0.5, hasteRating = 0.6, healingPower = 1, intellect = 0.093, spellDamage = 0.25, spellPower = 0.25, strength = 2.2, weaponDps = 14 },
		["Mountain King"] = { agility = 0.8, attackPower = 1, critRating = 0.5, defense = 1.5, dodge = 1.2, expertise = 1.5, hasteRating = 1.5, hitRating = 1.1, parry = 2, spellPower = 0.5, stamina = 2, strength = 4, weaponDps = 10 },
		["Wildwalker"] = { agility = 0.486, armorPenetration = 0.45, attackPower = 1, critRating = 0.65, expertise = 0.5, hasteRating = 0.6, strength = 2.2, weaponDps = 14 },
	},
	["Pyromancer"] = {
		["Draconic"] = { critRating = 1.614, hasteRating = 0.6, hitRating = 0.5, intellect = 0.218, spellDamage = 1, spellPenetration = 0.01, spellPower = 1 },
		["Flameweaving"] = { critRating = 0.9, hasteRating = 0.65, healingPower = 1, intellect = 0.129, spellDamage = 1, spellPower = 1, spirit = 2.182 },
		["Incineration"] = { critRating = 1.242, hasteRating = 0.6, hitRating = 0.5, intellect = 0.345, spellDamage = 1, spellPenetration = 0.01, spellPower = 1 },
	},
	["Ranger"] = {
		["Archery"] = { agility = 1.445, armorPenetration = 0.3, attackPower = 1, critRating = 0.631, hasteRating = 0.6, hitRating = 0.5, intellect = 0.054, rangedAttackPower = 1, rangedDps = 14, spellDamage = 0.15, spellPower = 0.15 },
		["Brigand"] = { agility = 1.567, armorPenetration = 0.45, attackPower = 1, critRating = 0.705, expertise = 0.5, hasteRating = 0.6, hitRating = 0.5, strength = 1, weaponDps = 14 },
		["Farstrider"] = { agility = 1.39, armorPenetration = 0.2, attackPower = 1, critRating = 0.53, hasteRating = 0.55, hitRating = 0.5, rangedAttackPower = 1 },
	},
	["Reaper"] = {
		["Domination"] = { agility = 1.53, armor = 0.37, armorPenetration = 1.35, attackPower = 1, critRating = 0.35, defense = 1.05, dodge = 0.9, expertise = 0.5, hasteRating = 0.35, hitRating = 0.5, parry = 0.9, stamina = 1.2, strength = 2.596, weaponDps = 14 },
		["Harvest"] = { agility = 0.471, armorPenetration = 0.45, attackPower = 1, critRating = 0.67, expertise = 0.5, hasteRating = 0.6, hitRating = 0.5, strength = 2.347, weaponDps = 14 },
		["Soul"] = { agility = 0.485, armorPenetration = 0.45, attackPower = 1, critRating = 0.689, expertise = 0.5, hasteRating = 0.6, strength = 2.2, weaponDps = 14 },
	},
	["Rogue"] = {
		["Assassination"] = { agility = 2, armorPenetration = 0.5, attackPower = 1, critRating = 0.8, expertise = 0.5, hasteRating = 0.6, hitRating = 0.5, strength = 1, weaponDps = 14 },
		["Combat"] = { agility = 2, armorPenetration = 1, attackPower = 1, critRating = 0.6, expertise = 0.5, hasteRating = 1, hitRating = 0.5, strength = 1, weaponDps = 14 },
		["Subtlety"] = { agility = 2, armorPenetration = 0.5, attackPower = 1, critRating = 0.7, expertise = 0.5, hasteRating = 0.6, hitRating = 0.5, strength = 1, weaponDps = 14 },
	},
	["Runemaster"] = {
		["Engravement"] = { agility = 1.429, attackPower = 1, critRating = 0.2, expertise = 0.5, hasteRating = 0.6, intellect = 0.109, spellDamage = 0.5, spellPower = 0.5, strength = 1.125, weaponDps = 14 },
		["Glyphic"] = { critRating = 0.69, hasteRating = 0.6, intellect = 0.239, spellDamage = 1, spellPenetration = 0.01, spellPower = 1, spirit = 0.33 },
		["Riftblade"] = { agility = 1.643, attackPower = 1, critRating = 0.2, expertise = 0.5, hasteRating = 0.6, intellect = 0.144, spellDamage = 0.25, spellPower = 0.25, strength = 1, weaponDps = 14 },
	},
	["Shaman"] = {
		["Elemental"] = { critRating = 0.9, hasteRating = 1, hitRating = 0.5, intellect = 0.2, spellPenetration = 0.5, spellPower = 1 },
		["Enhancement"] = { agility = 1, armorPenetration = 0.5, attackPower = 1, critRating = 0.5, expertise = 0.5, hasteRating = 0.5, hitRating = 0.5, intellect = 1, spellPower = 0.4, strength = 1, weaponDps = 14 },
		["Restoration"] = { critRating = 0.5, hasteRating = 0.5, healingPower = 1, intellect = 1, mp5 = 0.1, spellPower = 1, spirit = 0.1 },
	},
	["Starcaller"] = {
		["Moon Guard"] = { agility = 2.147, armor = 0.2, armorPenetration = 0.15, attackPower = 0.75, block = 0.75, blockValue = 0.26, critRating = 0.354, defense = 1.05, dodge = 0.9, expertise = 0.5, hasteRating = 0.35, hitRating = 0.5, intellect = 0.721, parry = 0.9, shieldBlockValue = 0.2, spellDamage = 1, spellPower = 1, stamina = 1.1, strength = 2.041, weaponDps = 14 },
		["Moon Priest"] = { critRating = 0.505, hasteRating = 0.65, healingPower = 1, intellect = 1, spellDamage = 1, spellPower = 1 },
		["Sentinel"] = { agility = 1.366, armorPenetration = 0.3, attackPower = 1, critRating = 0.778, hasteRating = 0.1, intellect = 2.1, rangedAttackPower = 1, rangedDps = 14, spellDamage = 0.25, spellPower = 0.25 },
		["Warden"] = { agility = 0.829, armorPenetration = 0.3, attackPower = 0.5, critRating = 0.7, hasteRating = 0.6, intellect = 2, spellDamage = 1, spellPenetration = 0.3, spellPower = 1, strength = 0.55, weaponDps = 14 },
	},
	["Stormbringer"] = {
		["Lightning"] = { critRating = 1.563, hasteRating = 0.6, hitRating = 0.5, intellect = 0.209, spellDamage = 1, spellPenetration = 0.01, spellPower = 1 },
		["Maelstrom"] = { critRating = 0.882, hasteRating = 0.6, intellect = 0.244, spellDamage = 1, spellPenetration = 0.01, spellPower = 1 },
		["Wind"] = { critRating = 0.5, hasteRating = 0.55, hitRating = 0.5, intellect = 0.067, spellDamage = 1, spellPower = 1 },
	},
	["Sun Cleric"] = {
		["Blessings"] = { critRating = 0.5, hasteRating = 0.65, healingPower = 1, intellect = 0.436, spellDamage = 1, spellPower = 1 },
		["Piety"] = { critRating = 1, hasteRating = 0.6, intellect = 0.21, spellDamage = 1, spellPenetration = 0.01, spellPower = 1 },
		["Seraphim"] = { agility = 1.32, armor = 0.256, armorPenetration = 0.15, attackPower = 0.5, block = 0.75, blockValue = 0.2, critRating = 0.363, defense = 1.05, dodge = 0.9, expertise = 0.5, hasteRating = 0.35, hitRating = 0.5, intellect = 1.089, parry = 0.9, shieldBlockValue = 0.2, spellDamage = 1, spellPower = 1, stamina = 1.15, strength = 3.053, weaponDps = 14 },
		["Valkyrie"] = { agility = 0.445, armorPenetration = 0.3, attackPower = 1.25, critRating = 0.625, expertise = 0.5, hasteRating = 0.6, intellect = 0.088, spellDamage = 0.25, spellPower = 0.25, strength = 3.36, weaponDps = 14 },
	},
	["Templar"] = {
		["Crusader"] = { agility = 1.713, armorPenetration = 0.3, attackPower = 1, critRating = 0.739, expertise = 0.5, hasteRating = 0.6, intellect = 0.215, spellDamage = 1, spellPower = 1, strength = 1.05, weaponDps = 14 },
		["Oathkeeper"] = { agility = 2.872, armor = 0.4, armorPenetration = 0.15, attackPower = 1, critRating = 0.35, defense = 1.05, dodge = 0.9, expertise = 0.5, hasteRating = 0.35, hitRating = 0.5, intellect = 0.2, parry = 0.9, stamina = 1.05, strength = 1.333, weaponDps = 14 },
		["Zealot"] = { agility = 1.4, armorPenetration = 0.1, attackPower = 1, critRating = 0.7, expertise = 0.5, hasteRating = 0.5, intellect = 0.7, spellDamage = 0.7, spellPower = 0.7, strength = 1.1, weaponDps = 14 },
	},
	["Tinker"] = {
		["Demolition"] = { agility = 1.878, armorPenetration = 0.3, attackPower = 1, critRating = 0.644, hasteRating = 0.6, intellect = 1.205, rangedAttackPower = 1, rangedDps = 14, spellDamage = 1, spellPower = 1 },
		["Invention"] = { critRating = 0.5, hasteRating = 0.65, healingPower = 1, intellect = 0.442, rangedDps = 14, spellDamage = 1, spellPower = 1 },
		["Mechanics"] = { agility = 1.375, armorPenetration = 0.3, attackPower = 1, critRating = 0.705, hasteRating = 0.6, intellect = 1.219, rangedAttackPower = 1, rangedDps = 14, spellDamage = 0.15, spellPower = 0.15 },
	},
	["Venomancer"] = {
		["Fortitude"] = { agility = 2.529, armor = 0.34, armorPenetration = 0.15, attackPower = 0.5, critRating = 0.357, defense = 1.05, dodge = 0.9, hasteRating = 0.35, intellect = 0.05, parry = 0.9, spellDamage = 1, spellPower = 1, stamina = 1, strength = 0.8, weaponDps = 14 },
		["Rotweaver"] = { critRating = 1.2, hasteRating = 0.6, hitRating = 0.5, intellect = 0.575, spellDamage = 1, spellPenetration = 0.01, spellPower = 1 },
		["Stalking"] = { agility = 0.4, attackPower = 0.2, critRating = 1, expertise = 0.5, hasteRating = 0.8, intellect = 1, spellDamage = 1, spellPenetration = 0.5, spellPower = 1 },
		["Vizier"] = { critRating = 0.5, hasteRating = 0.65, healingPower = 1, intellect = 0.4, spellDamage = 1, spellPower = 1 },
	},
	["Warlock"] = {
		["Affliction"] = { critRating = 0.8, hasteRating = 1, hitRating = 0.5, intellect = 0.1, spellPenetration = 0.5, spellPower = 1, spirit = 0.1 },
		["Demonology"] = { critRating = 0.5, hasteRating = 0.5, hitRating = 0.5, intellect = 0.1, spellPenetration = 0.5, spellPower = 1, spirit = 0.1, stamina = 0.01 },
		["Destruction"] = { critRating = 0.7, hasteRating = 0.8, hitRating = 0.5, intellect = 0.1, spellPenetration = 0.5, spellPower = 1, spirit = 0.1 },
	},
	["Warrior"] = {
		["Arms"] = { agility = 1, armor = 0.01, armorPenetration = 1, attackPower = 1, critRating = 0.5, expertise = 0.5, hasteRating = 0.5, hitRating = 0.5, strength = 2, weaponDps = 14 },
		["Fury"] = { agility = 1, armor = 0.01, armorPenetration = 1, attackPower = 1, critRating = 0.5, expertise = 0.5, hasteRating = 0.6, hitRating = 0.5, strength = 2, weaponDps = 14 },
		["Protection"] = { agility = 1, armor = 0.1, armorPenetration = 0.5, attackPower = 1, block = 1, blockValue = 1, critRating = 0.2, defense = 1, dodge = 1, expertise = 0.5, hasteRating = 0.2, hitRating = 0.5, parry = 1, stamina = 2, strength = 1, weaponDps = 14 },
	},
	["Witch Doctor"] = {
		["Brewing"] = { critRating = 0.5, hasteRating = 0.65, healingPower = 1, intellect = 0.07, spellDamage = 1, spellPower = 1, spirit = 0.3 },
		["Shadowhunting"] = { agility = 2, attackPower = 1, critRating = 0.672, hasteRating = 0.5, intellect = 1.2, rangedAttackPower = 1, rangedDps = 14, spellDamage = 0.2, spellPower = 0.2 },
		["Voodoo"] = { critRating = 1.238, hasteRating = 0.6, intellect = 0.173, spellDamage = 1, spellPenetration = 0.01, spellPower = 1, spirit = 1.504 },
	},
	["Witch Hunter"] = {
		["Black Knight"] = { agility = 3.326, armor = 0.4, armorPenetration = 0.15, attackPower = 1, critRating = 0.35, defense = 1.05, dodge = 0.9, expertise = 0.5, hasteRating = 0.35, hitRating = 0.5, intellect = 0.27, parry = 0.9, spellDamage = 0.75, spellPower = 0.75, stamina = 1, strength = 1.225, weaponDps = 14 },
		["Boltslinger"] = { agility = 1.395, armorPenetration = 0.3, attackPower = 1, critRating = 0.938, hasteRating = 0.6, intellect = 1.119, rangedAttackPower = 1, rangedDps = 14, spellDamage = 0.5, spellPower = 0.5 },
		["Houndmaster"] = { agility = 1.375, armorPenetration = 0.3, attackPower = 1, critRating = 0.891, hasteRating = 0.6, intellect = 0.336, rangedAttackPower = 1, rangedDps = 14, spellDamage = 0.5, spellPower = 0.5 },
		["Inquisition"] = { agility = 1.745, armorPenetration = 0.3, attackPower = 1, critRating = 0.644, expertise = 0.5, hasteRating = 0.6, intellect = 1.082, spellDamage = 0.75, spellPower = 0.75, strength = 1, weaponDps = 14 },
	},
}
